"""
Synthetic fallback adapter.

Generates arbitrage-consistent commodity option chains in the futures-option
shape (Black-76 world) so the whole pipeline runs end-to-end with zero external
access. This is the PRIMARY runnable path for the project; live adapters
(yfinance/EIA/CME) plug into the same schema when available.

Design goals:
  * Realistic term structure of forwards (contango/backwardation per commodity).
  * Realistic implied-vol smile/skew that varies by maturity.
  * Prices generated FROM a known vol surface via Black-76, so that when the
    surface module inverts prices back to IVs it recovers the input smile
    (a built-in sanity check / round-trip test).
  * Bid/ask spreads widen away from ATM and for longer maturities, mimicking
    liquidity thinning at the wings.

Because prices are generated by a no-arbitrage model on a coherent surface,
the arbitrage filters downstream should pass on clean data and only fire when
we deliberately inject stale/noisy quotes (which the generator can also do).
"""

from __future__ import annotations

import math
from datetime import date, timedelta
from typing import Sequence

import numpy as np
import pandas as pd

from data.schema import (
    Commodity,
    OptionType,
    QuoteSnapshot,
    coerce_to_schema,
    year_fraction,
)


# ---------------------------------------------------------------------------
# Per-commodity market character. These are deliberately hand-set to plausible
# regimes, not fitted to any proprietary data.
# ---------------------------------------------------------------------------
_COMMODITY_CONFIG = {
    Commodity.WTI: {
        "spot": 74.0,
        # forward curve slope: negative => backwardation (typical for crude)
        "curve_slope_per_yr": -1.8,
        "atm_vol": 0.33,
        # skew: puts bid over calls (crude tends to have downside skew in stress,
        # but a mild put skew is a reasonable base case)
        "skew": -0.12,       # d(vol)/d(log-moneyness), negative => put skew
        "smile_curv": 0.55,  # convexity of the smile
        "term_vol_slope": -0.04,  # vol slightly declines with maturity here
        "tick": 0.01,
    },
    Commodity.HENRY_HUB: {
        "spot": 2.85,
        # gas often in contango at the front; seasonal, but keep it simple
        "curve_slope_per_yr": 0.35,
        "atm_vol": 0.55,        # gas is much more volatile than oil
        "skew": 0.18,           # gas frequently shows CALL skew (upside spikes)
        "smile_curv": 0.9,
        "term_vol_slope": -0.08,
        "tick": 0.001,
    },
}

_MATURITY_MONTHS = [1, 2, 3, 6, 9, 12]  # option expiries to generate


def _forward(spot: float, slope_per_yr: float, t: float) -> float:
    """Simple linear forward curve in calendar time (years)."""
    return max(spot + slope_per_yr * t, 1e-6)


def _black76_price(F: float, K: float, T: float, sigma: float, r: float, is_call: bool) -> float:
    """Black-76 price of a European option on a future."""
    if T <= 0 or sigma <= 0:
        payoff = max(F - K, 0.0) if is_call else max(K - F, 0.0)
        return math.exp(-r * T) * payoff
    sqrtT = math.sqrt(T)
    d1 = (math.log(F / K) + 0.5 * sigma * sigma * T) / (sigma * sqrtT)
    d2 = d1 - sigma * sqrtT
    Nd1 = 0.5 * (1.0 + math.erf(d1 / math.sqrt(2.0)))
    Nd2 = 0.5 * (1.0 + math.erf(d2 / math.sqrt(2.0)))
    if is_call:
        return math.exp(-r * T) * (F * Nd1 - K * Nd2)
    return math.exp(-r * T) * (K * (1.0 - Nd2) - F * (1.0 - Nd1))


def _smile_vol(cfg: dict, log_moneyness: float, T: float) -> float:
    """
    Implied vol as a function of log-moneyness ln(K/F) and maturity T.
    Quadratic-in-log-moneyness smile with a maturity-dependent ATM level.
    """
    atm = cfg["atm_vol"] + cfg["term_vol_slope"] * T
    vol = atm + cfg["skew"] * log_moneyness + cfg["smile_curv"] * log_moneyness ** 2
    return float(max(vol, 0.05))


def _strikes_for(F: float, n: int, width: float) -> np.ndarray:
    """n strikes spread log-uniformly around the forward, +/- `width` in log space."""
    grid = np.linspace(-width, width, n)
    return np.round(F * np.exp(grid), 4)


def _bidask_spread(mid: float, atm_dist: float, T: float, tick: float) -> tuple[float, float]:
    """
    Half-spread grows with distance from ATM and with maturity.
    atm_dist is |log-moneyness|. Returns (bid, ask), floored at one tick.
    """
    base = 0.02 + 0.06 * atm_dist + 0.03 * T      # fractional half-spread
    half = max(mid * base, tick)
    bid = max(mid - half, tick)
    ask = mid + half
    return round(bid, 4), round(ask, 4)


class SyntheticAdapter:
    """Generates a full, arb-consistent snapshot with no external dependencies."""

    name = "synthetic"

    def __init__(
        self,
        r: float = 0.045,
        strikes_per_maturity: int = 9,
        seed: int | None = 7,
        inject_noise: bool = False,
    ) -> None:
        if not (7 <= strikes_per_maturity <= 11):
            raise ValueError("strikes_per_maturity should be 7-11 to match the project scope")
        self.r = r
        self.n_strikes = strikes_per_maturity
        self.rng = np.random.default_rng(seed)
        self.inject_noise = inject_noise

    def fetch(
        self,
        commodities: Sequence[Commodity],
        as_of: date | None = None,
    ) -> QuoteSnapshot:
        as_of = as_of or date.today()
        rows: list[dict] = []

        for commodity in commodities:
            cfg = _COMMODITY_CONFIG[commodity]
            for m in _MATURITY_MONTHS:
                expiry = as_of + timedelta(days=int(round(m * 30.4)))
                # Single source of truth for time-to-maturity: derive it from the
                # stored dates with ACT/365, exactly as downstream (surface/pricing)
                # code will. Never carry a separate "m/12" clock, or generated
                # prices and re-derived IVs will disagree.
                T = year_fraction(as_of, expiry)
                F = _forward(cfg["spot"], cfg["curve_slope_per_yr"], T)
                # wing width scales a bit with vol and maturity
                width = 0.12 + 0.9 * cfg["atm_vol"] * math.sqrt(T)
                strikes = _strikes_for(F, self.n_strikes, width)

                for K in strikes:
                    lm = math.log(K / F)
                    sigma = _smile_vol(cfg, lm, T)
                    # price OTM side to mimic what actually quotes: calls above F,
                    # puts below F (standard for a liquid chain)
                    is_call = K >= F
                    opt = OptionType.CALL if is_call else OptionType.PUT
                    mid = _black76_price(F, K, T, sigma, self.r, is_call)

                    if self.inject_noise and self.rng.random() < 0.05:
                        # deliberately corrupt ~5% of quotes (stale/crossed) so the
                        # downstream validation/arb filters have something to catch
                        mid *= self.rng.uniform(0.5, 1.6)

                    bid, ask = _bidask_spread(mid, abs(lm), T, cfg["tick"])
                    rows.append(
                        {
                            "commodity": commodity,
                            "as_of": as_of,
                            "expiry": expiry,
                            "future_expiry": expiry,
                            "forward": round(F, 4),
                            "strike": float(K),
                            "option_type": opt,
                            "bid": bid,
                            "ask": ask,
                            "volume": int(self.rng.integers(0, 5000)),
                            "open_interest": int(self.rng.integers(0, 20000)),
                            # stash the true vol and the unrounded mid so tests can
                            # verify the round-trip without tick-rounding artifacts
                            "_true_iv": round(sigma, 6),
                            "_raw_mid": mid,
                        }
                    )

        df = pd.DataFrame(rows)
        true_iv = df.pop("_true_iv")
        raw_mid = df.pop("_raw_mid")
        frame = coerce_to_schema(df, source=self.name)
        return QuoteSnapshot(
            frame=frame,
            as_of=as_of,
            source=self.name,
            meta={
                "r": self.r,
                "strikes_per_maturity": self.n_strikes,
                "true_iv": true_iv.to_numpy(),   # aligned to frame row order
                "raw_mid": raw_mid.to_numpy(),   # unrounded mid, aligned to frame row order
                "note": "prices generated via Black-76 on a known smile; invert raw_mid to recover true_iv",
            },
        )


if __name__ == "__main__":
    adapter = SyntheticAdapter()
    snap = adapter.fetch([Commodity.WTI, Commodity.HENRY_HUB])
    print(snap.summary().to_string(index=False))
    print("\nTotal quotes:", len(snap.frame))
    print("Sources:", snap.frame['source'].unique())
